### ISSUE TITLE
add manual metadata filter

### ISSUE THREAD

**Issue by mcnewcp** [Overtrained/contextual-qa-chat-app#14]
The self querying retriever doesn't seem reliable once I look at the details.  An acceptable alternative would be to add manual metadata filters to allow the user to select any combination of metadata values.  This will be useful for upcoming use cases.  The pinecone filtering docs are [here](https://docs.pinecone.io/docs/metadata-filtering).
## Tasks

- [x] generate a list of all subreddits in vector database
- [x] add all subreddits as checkbox filter option in UI
- [x] add filter argument to retriever
